Move to setuptools
setuptools absorbed distutils anyway, and some package managers (notably
sdispater/poetry) will choke trying to install this repo as-is. Moving
to setuptools fixes this issue.

An example of the error from poetry is:

```
[VenvCommandError]
Command ['python', 'setup.py', 'egg_info'] errored with the following output:
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help
error: invalid command 'egg_info'
```